name: Sync Image to Aliyun  Example
 
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Git pull
      uses: actions/checkout@v3
 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-8ezl3ueicx1ysamd.cn-guangzhou.personal.cr.aliyuncs.com
        username: ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: false
 
    # 使用shell命令批量同步所需的镜像到阿里云个人仓库中
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        # 使用 skopeo 工具将镜像同步到阿里云个人仓库中，使用时请自行源和目标修改仓库名称和镜像名称
         kopeo copy docker://docker.io/Yxiao001/redis:7.2.6 docker://crpi-8ezl3ueicx1ysamd.cn-guangzhou.personal.cr.aliyuncs.com/docker_images_ye/redis:7.2.6
